plugins {
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
}

def modVersion = mod_version
def mcVersion = minecraft_version
def loaderName = 'forge'

version = modVersion
group = 'net.shishen575.create_upgrades'
base {
    archivesName = 'create_upgrades'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'parchment', version: "${parchment_mappings_version}-${parchment_minecraft_version}"

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            mods { create_upgrades { source sourceSets.main } }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            args '--nogui'
            mods { create_upgrades { source sourceSets.main } }
        }
    }
}

repositories {
    maven { url = "https://maven.createmod.net" }
    maven { url = "https://maven.tterrag.com" }
    mavenCentral()
}

dependencies {
    minecraft("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    implementation(fg.deobf("com.simibubi.create:create-${minecraft_version}:${create_version}:slim")) { transitive = false }
    implementation(fg.deobf("com.jozufozu.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}"))
}

jar {
    archiveFileName = "Create_Upgrades-${mcVersion}-${modVersion}.jar"
    manifest {
        attributes([
            'Specification-Title'     : 'create_upgrades',
            'Specification-Vendor'    : 'shishen575',
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.jar.archiveVersion,
            'Implementation-Vendor'   : 'shishen575',
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
            'MixinConfigs'            : 'create_upgrades.mixins.json'
        ])
    }
}
